In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv("../dataset/selected_features_data.csv")

data.head()

,tenure,MonthlyCharges,TotalCharges,Contract,OnlineSecurity_Yes,TechSupport_Yes,InternetService_Fiber optic,Churn
0,1,29.85,29.85,0.0,0.0,0.0,0.0,0
1,34,56.95,1889.50,1.0,1.0,0.0,0.0,0
2,2,53.85,108.15,0.0,1.0,0.0,0.0,1
3,45,42.30,1840.75,1.0,1.0,1.0,0.0,0
4,2,70.70,151.65,0.0,0.0,0.0,1.0,1

In [19]:
x=data.drop(columns=["Churn"])  # DataFrame (2D)
y=data["Churn"]       # Series (1D)

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [21]:
x_train.head()

,tenure,MonthlyCharges,TotalCharges,Contract,OnlineSecurity_Yes,TechSupport_Yes,InternetService_Fiber optic
2142,21,64.85,1336.800,1.0,1.0,0.0,0.0
1623,54,97.20,5129.450,2.0,0.0,0.0,1.0
6074,1,23.45,23.450,0.0,0.0,0.0,0.0
1362,4,70.20,237.950,0.0,0.0,0.0,1.0
6754,0,61.90,1397.475,2.0,1.0,1.0,0.0

In [16]:
x_test.head()

,tenure,MonthlyCharges,TotalCharges,Contract,OnlineSecurity_Yes,TechSupport_Yes,InternetService_Fiber optic
185,1,24.80,24.80,0.0,0.0,0.0,0.0
2715,41,25.25,996.45,0.0,0.0,0.0,0.0
3825,52,19.35,1031.70,2.0,0.0,0.0,0.0
1807,1,76.35,76.35,0.0,0.0,0.0,1.0
132,67,50.55,3260.10,2.0,0.0,1.0,0.0

In [22]:
x_train.shape,x_test.shape

((5634, 7), (1409, 7))

In [32]:
#Logistic Regression

lr=LogisticRegression(max_iter=1000)
lr.fit(x_train,y_train)

y_pred_lr=lr.predict(x_test)
lr_accuracy=accuracy_score(y_test,y_pred_lr)
print("Logistic Regression Accuracy:", lr_accuracy)

Logistic Regression Accuracy: 0.8055358410220014

In [31]:
#Decision Tree

dt=DecisionTreeClassifier(random_state=42)
dt.fit(x_train,y_train)

y_pred_dt=dt.predict(x_test)
dt_accuracy=accuracy_score(y_test,y_pred_dt)
print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.730305180979418

In [ ]:
#Random Forest Classifier

rf = RandomForestClassifier(random_state=42)

rf.fit(x_train, y_train)

rf_pred = rf.predict(x_test)

rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest:", rf_accuracy)

Random Forest: 0.7721788502484032

In [30]:
#Gradient Boosting Classifier

gb = GradientBoostingClassifier(random_state=42)

gb.fit(x_train, y_train)

gb_pred = gb.predict(x_test)

gb_accuracy = accuracy_score(y_test, gb_pred)

print("Gradient Boosting:", gb_accuracy)

Gradient Boosting: 0.8026969481902059

In [33]:

import pandas as pd
results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Gradient Boosting"
    ],
    "Accuracy": [
        lr_accuracy,
        dt_accuracy,
        rf_accuracy,
        gb_accuracy
    ]
})

In [36]:
results

                 Model  Accuracy
0  Logistic Regression  0.805536
1        Decision Tree  0.730305
2        Random Forest  0.772179
3    Gradient Boosting  0.802697