In [22]:
import pickle
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [7]:
data = pd.read_csv("../dataset/selected_features_data.csv")

data.head()

,tenure,MonthlyCharges,TotalCharges,Contract,OnlineSecurity_Yes,TechSupport_Yes,InternetService_Fiber optic,Churn
0,1,29.85,29.85,0.0,0.0,0.0,0.0,0
1,34,56.95,1889.50,1.0,1.0,0.0,0.0,0
2,2,53.85,108.15,0.0,1.0,0.0,0.0,1
3,45,42.30,1840.75,1.0,1.0,1.0,0.0,0
4,2,70.70,151.65,0.0,0.0,0.0,1.0,1

In [12]:
x= data.drop("Churn", axis=1)

y= data["Churn"]

In [13]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.20,
    random_state=42
)

In [14]:
model = pickle.load(open("../models/logistic_regression.pkl", "rb"))

In [15]:
model = pickle.load(
    open("../models/logistic_regression.pkl", "rb")
)

print("Model Loaded Successfully")

Model Loaded Successfully

In [16]:
y_pred = model.predict(x_test)

In [17]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8055358410220014

In [18]:
precision = precision_score(y_test, y_pred)

print("Precision:", precision)

Precision: 0.6666666666666666

In [19]:
recall = recall_score(y_test, y_pred)

print("Recall:", recall)

Recall: 0.5308310991957105

In [20]:
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)

F1 Score: 0.591044776119403

In [21]:
y_prob = model.predict_proba(x_test)[:, 1]

roc_auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC Score:", roc_auc)

ROC-AUC Score: 0.855257641785792

In [23]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1036
           1       0.67      0.53      0.59       373

    accuracy                           0.81      1409
   macro avg       0.75      0.72      0.73      1409
weighted avg       0.80      0.81      0.80      1409

In [24]:
results = pd.DataFrame({
    "Metric": [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score",
        "ROC-AUC"
    ],
    "Value": [
        accuracy,
        precision,
        recall,
        f1,
        roc_auc
    ]
})

results

      Metric     Value
0   Accuracy  0.805536
1  Precision  0.666667
2     Recall  0.530831
3   F1 Score  0.591045
4    ROC-AUC  0.855258

In [ ]:
"""Logistic Regression was selected as the final model and achieved satisfactory performance with an accuracy of 80.55% and ROC-AUC score of 85.53%. The model can effectively predict customer churn and help the company identify at-risk customers for retention strategies."""